# Generated by Django 5.1 on 2024-08-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengedetail',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
