# Generated by Django 5.1 on 2024-08-14 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengedetail',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengedetail',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='submission',
            name='time_taken',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
