# Generated by Django 5.1 on 2024-08-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_challengedetail_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='DiscussionThread',
        ),
    ]
