# Generated by Django 5.1 on 2025-05-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_submission_reject_reason_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AddField(
            model_name="challenge",
            name="is_combination",
            field=models.BooleanField(
                default=False,
                help_text="True if this challenge combines multiple challenges",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="is_dlc",
            field=models.BooleanField(
                default=False, help_text="True if this challenge requires DLC content"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
