# Generated by Django 5.1 on 2025-05-24 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_add_challenge_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="base_points",
            field=models.IntegerField(
                default=0, help_text="Base points for completing this challenge"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="points_awarded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="challenges_completed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Hard", "Hard"),
                    ("Extreme", "Extreme"),
                ],
                max_length=50,
            ),
        ),
    ]
