# Generated by Django 5.1 on 2025-05-24 22:20

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_challenge_base_points_submission_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="challenge",
            name="estimated_completion_time",
            field=models.DurationField(
                blank=True,
                help_text="Estimated time to complete this challenge (HH:MM:SS)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="admin_verified_time",
            field=models.DurationField(
                blank=True,
                help_text="Admin-verified completion time (overrides user time if set)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="submission",
            name="time_taken",
            field=models.DurationField(
                default=datetime.timedelta(0),
                help_text="Time taken to complete this challenge (HH:MM:SS)",
            ),
        ),
    ]
