# Generated by Django 5.1 on 2025-05-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_user_profile_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Elden Ring Challenges", max_length=100),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="A platform for Elden Ring challenge runs"
                    ),
                ),
                ("enable_registrations", models.BooleanField(default=True)),
                ("enable_submissions", models.BooleanField(default=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "notification_email",
                    models.EmailField(default="admin@eldenring.com", max_length=254),
                ),
                ("max_submissions_per_day", models.IntegerField(default=5)),
                ("auto_approve_submissions", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
