# Generated by Django 5.1 on 2025-05-25 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_sitesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="estimated_completion_time",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="admin_verified_time",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="base_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="submission",
            name="time_taken",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
