# Generated by Django 5.1 on 2025-05-25 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_challenge_estimated_completion_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="user",
            name="completed_challenges",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
    ]
