# Generated by Django 5.1 on 2025-05-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_user_badges_remove_user_completed_challenges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="admin_verified_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
