# Generated by Django 5.1 on 2025-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_submission_admin_verified_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="completed_challenges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="max_submissions_per_day",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="challenges_completed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="total_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
