# Generated by Django 5.1 on 2025-06-01 23:43

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_user_badges_user_completed_challenges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[api.validators.validate_email_format],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[api.validators.validate_username],
            ),
        ),
    ]
